name: Bug Report
description: File a bug report by using form.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["ChatApp"]
assignees:
  - wiktorKycia
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browsers are you seeing the problem on?
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
        - Opera
        - Brave
      default: 0
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which device type are you running?
      options:
        - Desktop
        - Mobile
        - Tablet
      default: 0
    validations:
      required: true
  - type: dropdown
    id: bugtype
    attributes:
      label: BugType
      description: Which type of bug have you encountered?
      options:
        - styling
        - client side
        - server side
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: If you have anything to add more, please tell me!
      placeholder: ""
      value: ""
    validations:
      required: false
